---
name: publish-docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code@scm
        uses: actions/checkout@main
      - name: checkout-ghpages@scm
        uses: actions/checkout@main
        with:
          ref: gh-pages
          path: docs/build/html

      - name: setup@python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'

      - name: setup@poetry
        run: pip install poetry

      - name: setup@venv
        run: poetry install

      - name: docs@sphinx
        run: |
          cd docs
          poetry run make html

      - name: publish@scm
        run: |
          cd docs/build/html
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":construction_worker: publish documentation" --allow-empty
          git push origin gh-pages
