---
name: run-test-suite

on: [push]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@scm
        uses: actions/checkout@main

      - name: setup@python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'

      - name: setup@poetry
        run: pip install poetry

      - name: setup@venv
        run: poetry install

      - name: lint@black
        run: poetry run black --check triotp --target-version py310

      - name: test@pytest
        run: poetry run pytest --cov triotp --cov-report xml

      - name: coverage@coveralls
        run: poetry run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}