---
name: run-test-suite

on: [push]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@scm
        uses: actions/checkout@main

      - name: setup@python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'

      - name: setup@venv
        run: pdm install

      - name: lint@black
        run: pdm run black --check src/ --target-version py310

      - name: test@pytest
        run: pdm run pytest --cov src/ --cov-report xml

      - name: coverage@coveralls
        run: pdm run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
